language: node_js
sudo: false
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
node_js:
  - '0.10'
  - '0.12'
  - 'iojs'
  - '4'
after_script:
  - npm install coveralls && cat ./coverage/lcov.info | coveralls
